version: '3.7'

services:
  mysqlDb:
    container_name: nlw-copa
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: nlw-copa
      MYSQL_USER: micael
      MYSQL_PASSWORD: 123
    ports:
      - '9906:3306'
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - production-network
networks:
    production-network:
        driver: bridge
